# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-29 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='flowcell',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('label', models.TextField()),
                ('status', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('qc_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='index',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('kid', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='kit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('mid', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='manufacturer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flowcell_id', models.IntegerField()),
                ('project_id', models.IntegerField()),
                ('sample_id', models.IntegerField()),
                ('flowcell_element_id', models.IntegerField()),
                ('flowcell_element_control', models.IntegerField()),
                ('flowcell_element_conc', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('title', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.TextField()),
                ('name', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=500)),
                ('pi', models.CharField(max_length=500)),
                ('billing_account', models.CharField(max_length=500)),
                ('department', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='sample',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('project_id', models.IntegerField()),
                ('label', models.CharField(max_length=500)),
                ('project_description', models.CharField(max_length=500)),
                ('organism', models.CharField(max_length=500)),
                ('sequencer', models.CharField(max_length=500)),
                ('alignment_genome', models.CharField(max_length=500)),
                ('sample_type', models.CharField(max_length=500)),
                ('determined_by', models.CharField(max_length=100)),
                ('dna_conc_ul', models.FloatField()),
                ('avg_len_lib', models.CharField(max_length=50)),
                ('sample_vol', models.FloatField()),
                ('read_length', models.CharField(max_length=50)),
                ('sample_prep_kit', models.IntegerField()),
                ('kit_other', models.CharField(max_length=500)),
                ('index_type', models.TextField()),
                ('comments', models.TextField()),
                ('other_variables', models.TextField()),
                ('sequence_url', models.TextField()),
                ('quality_url', models.TextField()),
                ('status', models.TextField()),
            ],
        ),
    ]
